---
# NOTE: the "ansible" role isn't included here, because we want to stop and restart Ansible after
#       that, just in case it was updated
- name: Setup the nCoda development environment.
  hosts: localhost
  connection: local

  roles:
    - { role: repositories, repo_stage: 'init', tags: 'init' }
    - { role: repositories, repo_stage: 'fetch', tags: 'fetch' }
    - { role: repositories, repo_stage: 'pull', tags: 'pull' }
    - { role: python, tags: 'init' }
    - { role: lychee, tags: ['update', 'update_lychee', 'init'] }
    - { role: hgdemo, tags: 'init' }
    - { role: nodejs, tags: 'init' }
    - { role: julius, tags: ['update', 'update_julius', 'init'] }
    - { role: watchman, tags: 'init' }
    - { role: nc_scripts, tags: ['update', 'update_ncoda', 'init'] }
