---
# NOTE: the "ansible" role isn't included here, because we want to stop and restart Ansible after
#       that, just in case it was updated
- name: Setup the nCoda development environment.
  hosts: localhost
  connection: local

  roles:
    - { role: repositories, repo_stage: 'init' }
    - { role: repositories, repo_stage: 'fetch', tags: "fetch" }
    - python
    - { role: lychee, tags: ["update", "update_lychee"] }
    - hgdemo
    - nodejs
    - { role: julius, tags: ["update", "update_julius"] }
    - watchman
    - { role: nc_scripts, tags: ["update", "update_ncoda"] }
