---
# NOTE: the "ansible" role isn't included here, because we want to stop and restart Ansible after
#       that, just in case it was updated
- name: Setup the nCoda development environment.
  hosts: localhost
  connection: local

  roles:
    - repositories
    - { role: lychee, tags: ["update", "update_lychee"] }
    - { role: julius, tags: ["update", "update_julius"] }
    - watchman
    - { role: nc_scripts, tags: ["update", "update_ncoda"] }

# TODO:
# - finish watchman
# - template script for the "nc" commands below
#
# - in the "nc" command:
#   - restart [fujian|julius] (default "all")
#   - activate [lychee|ansible|julius] (activate which virtualenv? Default lychee. Or export aliases for "node" and "npm")
#
# - consider git hooks that tell you when your dependencies are out-of-sync
