---
# NOTE: the "ansible" role isn't included here, because we want to stop and restart Ansible after
#       that, just in case it was updated
- name: Setup the nCoda development environment.
  hosts: localhost
  connection: local

  roles:
    - repositories
    - { role: lychee, tags: ["update", "update_lychee"] }
    - { role: julius, tags: ["update", "update_julius"] }
    - watchman
    - nc_scripts

# TODO:
# - finish watchman
# - template script for the "nc" commands below
#
# - in the "nc" command:
#   - reset (clean up the "hgdemo" repository)
#   - restart [fujian|julius] (default "all")
#   - activate [lychee|ansible|julius] (activate which virtualenv? Default lychee. Or export aliases for "node" and "npm")
#
# - consider git hooks that tell you when your dependencies are out-of-sync
# - generate the "nc" file itself with Ansible, first from the "init.sh" then from "nc update ncoda"
#   - update the "update" command with a thing to regenerate the "ncoda" scripts
