---
# NOTE: the "ansible" role isn't included here, because we want to stop and restart Ansible after
#       that, just in case it was updated
- name: Setup the nCoda development environment.
  hosts: localhost
  connection: local

  roles:
    - { role: repositories, repo_stage: 'init' }
    - { role: repositories, repo_stage: 'fetch', tags: "fetch" }
    - python
    - { role: lychee, tags: ["update", "update_lychee"] }
    - hgdemo
    - nodejs
    - { role: julius, tags: ["update", "update_julius"] }
    - watchman
    - { role: nc_scripts, tags: ["update", "update_ncoda"] }

# TODO:
# - finish these for Mac OS X:
#   - Python
#     - ensure Lychee's virtualenv uses homebrew Python
#   - Git
#   - NPM
#   - watchman
#   - general testing
# - finish these for Windows:
#   - Python
#   - Git
#   - NPM
#   - watchman
#   - general testing
#
# - advanced additions for the "nc" command:
#   - restart [fujian|julius] (default "all")
#   - activate [lychee|ansible|julius] (activate which virtualenv? Default lychee. Or export aliases for "node" and "npm")
#
# - consider git hooks that tell you when your dependencies are out-of-sync
