---
- name: compile the Julius JavaScript
  command: '{{ node_path }} {{ repo_directory }}/julius/node_modules/.bin/browserify "{{ repo_directory }}/julius/js/ncoda-init.js" -o "{{ repo_directory }}/julius/js/ncoda-compiled.js" --ignore-missing'

- name: compile the Julius CSS
  command: '{{ node_path }} {{ repo_directory }}/julius/node_modules/.bin/lessc --clean-css "{{ repo_directory }}/julius/css/ncoda/main.less" "{{ repo_directory }}/julius/css/ncoda/main.css"'

- name: copy the Julius repository
  command: cp -R {{ repo_directory }}/julius {{ snapshot_dir }}
  args:
    creates: "{{ snapshot_dir }}/julius"
