---
- name: install libxml/libxslt for lxml (RedHat family)
  package: name={{ item }} state=present
  become: yes
  when: ansible_os_family == "RedHat"
  with_items:
    - libxml2
    - libxslt
    - libxml2-devel
    - libxslt-devel
- name: install libxml/libxslt for lxml (Debian family)
  package: name={{ item }} state=present
  become: yes
  when: ansible_os_family == "Debian"
  with_items:
    - libxml2
    - libxslt1.1
    - libxml2-dev
    - libxslt1-dev
