---
- name: make the virtualenv
  pip:
    virtualenv: "{{ lychee_venv_dir }}"
    virtualenv_command: "{{ ansible_venv_dir }}/bin/virtualenv"
    virtualenv_python: "{{ lychee_venv_python }}"
    state: latest
    name: "pip setuptools"

# NOTE: the order of the items below is important (Fujian depends on Lychee depends on mercurial-hug)
- name: install locally-cloned packages
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/{{ item }} state=present extra_args="-e"
  with_items:
    - mercurial-hug
    - lychee[devel]
    - fujian
