---
- name: make the virtualenv
  pip:
    virtualenv: "{{ lychee_venv_dir }}"
    virtualenv_command: "{{ ansible_venv_dir }}/bin/virtualenv"
    virtualenv_python: "{{ lychee_venv_python }}"
    state: latest
    name: "pip setuptools"

- name: install straight-forward requirements
  pip: virtualenv={{ lychee_venv_dir }} requirements={{ repo_directory }}/lychee/ncoda_requirements.txt

- name: install Mercurial-Hug
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/mercurial-hug state=present extra_args="-e"

- name: install Fujian
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/fujian state=present extra_args="-e"

- name: install Lychee
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/lychee state=present extra_args="-e"
