---
- name: make the virtualenv
  pip:
    virtualenv: "{{ lychee_venv_dir }}"
    virtualenv_command: "{{ ansible_venv_dir }}/bin/virtualenv"
    virtualenv_python: "{{ lychee_venv_python }}"
    state: latest
    name: "pip setuptools"

- name: install requirements from PyPI
  pip: virtualenv={{ lychee_venv_dir }} requirements={{ repo_directory }}/lychee/ncoda_requirements.txt

- name: install locally-cloned packages
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/{{ item }} state=present extra_args="-e"
  with_items:
    - fujian
    - lychee
    - mercurial-hug
