---
- name: make the virtualenv
  pip:
    virtualenv: "{{ lychee_venv_dir }}"
    state: latest
    name: "{{ item }}"
  with_items:
    - setuptools
    - pip

- name: install straight-forward requirements
  pip: virtualenv={{ lychee_venv_dir }} requirements={{ repo_directory }}/lychee/ncoda_requirements.txt

- name: install Mercurial-Hug
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/mercurial-hug state=present extra_args="-e"

- name: install Fujian
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/fujian state=present extra_args="-e"

- name: see whether Abjad is already installed
  stat: path={{ repo_directory }}/abjad
  register: abjad_stat
- name: download Abjad
  get_url:
    url: https://ncodamusic.org/abjad_7e3af7f.tar.xz
    dest: "{{ repo_directory }}/abjad.tar.xz"
    checksum: "sha256:aa3ae5cc534cbacb96a6125ba62855ce1639e4d647cbbe7b1d56bddf329cede6"
  when: not abjad_stat.stat.exists
- name: make a directory for Abjad
  file: name={{ repo_directory }}/abjad state=directory
  when: not abjad_stat.stat.exists
- name: unarchive Abjad
  unarchive:
    copy: no
    src: "{{ repo_directory }}/abjad.tar.xz"
    dest: "{{ repo_directory }}/abjad"
  when: not abjad_stat.stat.exists
- name: install Abjad
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/abjad state=present extra_args="-e"

- name: install Lychee
  pip: virtualenv={{ lychee_venv_dir }} name={{ repo_directory }}/lychee state=present extra_args="-e"
