---
- name: install Julius NPM libraries
  npm:
    executable: "{{ npm_path }}"
    path: "{{ repo_directory }}/julius"
    production: no
    state: present

- name: run an NPM deduplication
  command: "{{ npm_path }} dedupe chdir={{ repo_directory }}/julius"
