---
- name: make the repositories directory
  file: name={{ repo_directory }} state=directory

- name: clone the Git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ repo_directory }}/{{ item.name }}"
    force: no
    update: no
    recursive: yes
  with_items: "{{ git_repositories }}"

- name: clone the Mercurial repositories
  hg:
    repo: "{{ item.repo }}"
    dest: "{{ repo_directory }}/{{ item.name }}"
    force: no
    update: no
  with_items: "{{ hg_repositories }}"
