---
- name: make a gitignore file
  template: src=gitignore.j2 dest={{ ansible_env.PWD }}/.gitignore
- name: install Git
  package: name=git state=present
- name: install Mercurial
  pip: name=Mercurial version={{ hg_version }} state=present

- include: init.yml
  when: repo_stage == 'init'
