---
- name: make a gitignore file
  template: src=gitignore.j2 dest={{ ansible_env.PWD }}/.gitignore
- name: install Git
  package: name=git state=present
- name: install Mercurial
  pip: name=Mercurial version={{ hg_version }} state=present

- name: see whether the repositories were cloned
  stat: path={{ repo_directory }}
  register: repodir_stat
- include: init.yml
  when: not repodir_stat.stat.exists
- include: update.yml
  when: repodir_stat.stat.exists
