---
- name: make a gitignore file
  template: src=gitignore.j2 dest={{ repository_root }}/.gitignore
- name: install Git
  become: yes
  package: name=git state=present
- name: install Mercurial
  pip: name=Mercurial version={{ hg_version }} state=present

- name: see whether the user has Phabricator's SSH host key
  command: ssh-keygen -F goldman.ncodamusic.org
  ignore_errors: yes
  register: keycheck
- name: add Phabricator's SSH host key to the "known_hosts" file
  lineinfile:
    dest: "~/.ssh/known_hosts"
    insertafter: EOF
    line: "{{ phabricator_keyscan }}"
    state: present
  when: keycheck.stdout|length == 0

- include: init.yml
  when: repo_stage == 'init'

- include: fetch.yml
  when: repo_stage == 'fetch'

- include: pull.yml
  when: repo_stage == 'pull'

- name: generate "retired_warn" script
  template:
    src: retired_warn.py.j2
    dest: "{{ retired_warn_path }}"
    mode: u=rwx,g=rx,o=
- name: detect retired repositories still present
  shell: "python {{ retired_warn_path }}"
  register: retired_repos_return
- name: warn about retired repositories still present
  debug: msg={{ retired_repos_return.stdout }}
  when: retired_repos_return.stdout
