---
- name: pull the Git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ repo_directory }}/{{ item.name }}"
    force: no
    update: yes
    recursive: yes
  with_items: "{{ git_repositories }}"

- name: update the Mercurial repositories
  hg:
    repo: "{{ item.repo }}"
    dest: "{{ repo_directory }}/{{ item.name }}"
    force: no
    update: yes
  with_items: "{{ hg_repositories }}"
