---
- name: add the "nCoda Watchman" repository
  yum_repository:
    name: 'ncoda_watchman'
    description: 'nCoda Watchman'
    baseurl: 'http://download.opensuse.org/repositories/home:/crantila:/watchman/RHEL_7/'
    gpgcheck: yes
    gpgkey: 'http://download.opensuse.org/repositories/home:/crantila:/watchman/RHEL_7/repodata/repomd.xml.key'
    enabled: yes
  become: yes
  become_method: sudo

- name: install Watchman
  package: name=watchman state=present
  become: yes
  become_method: sudo

- name: set the path to Watchman
  set_fact: path_to_watchman='/usr/bin/watchman-make'
